.global start
.section .init, "ax"

start:
    addi x1, x0, 7
    sw x1, 0(x0)
    slli x1, x1, 1
    sw x1, 0(x0)
    slli x1, x1, 1
    sw x1, 0(x0)
    slli x1, x1, 1
    sw x1, 0(x0)
    slli x1, x1, 1
    sw x1, 0(x0)
    slli x1, x1, 1
    sw x1, 0(x0)
    slli x1, x1, 1
    sw x1, 0(x0)
    slli x1, x1, 1
    sw x1, 0(x0)
    slli x1, x1, 1
    sw x1, 0(x0)
    slli x1, x1, 1
    sw x1, 0(x0)
    slli x1, x1, 1
    sw x1, 0(x0)
    slli x1, x1, 1
    sw x1, 0(x0)
    slli x1, x1, 1
    sw x1, 0(x0)
    slli x1, x1, 1
    sw x1, 0(x0)
    slli x1, x1, 1
    sw x1, 0(x0)
    slli x1, x1, 1
    sw x1, 0(x0)
    srai x1, x1, 1
    sw x1, 0(x0)
    srli x1, x1, 1
    sw x1, 0(x0)
    srli x1, x1, 1
    sw x1, 0(x0)
    srli x1, x1, 1
    sw x1, 0(x0)
    srli x1, x1, 1
    sw x1, 0(x0)
    srli x1, x1, 1
    sw x1, 0(x0)
    srli x1, x1, 1
    sw x1, 0(x0)
    srli x1, x1, 1
    sw x1, 0(x0)
    srli x1, x1, 1
    sw x1, 0(x0)
    srli x1, x1, 1
    sw x1, 0(x0)
    srli x1, x1, 1
    sw x1, 0(x0)
    srli x1, x1, 1
    sw x1, 0(x0)
    srli x1, x1, 1
    sw x1, 0(x0)
    srli x1, x1, 1
    sw x1, 0(x0)
    srli x1, x1, 1
    sw x1, 0(x0)
    srli x1, x1, 1
    sw x1, 0(x0)
end:
